<a href="https://colab.research.google.com/github/Reynaldo-S/DE_Tasks/blob/main/Census_Data_Standardization_and_Analysis_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Census Data Standardization and Analysis Pipeline**

The inital steps invovles  and

1.   importing pandas library
2.   loading the excel file and converting them into a Dataframe.

In [4]:
#Importing pandas lib
import pandas as pd

#loading the excel
path="/content/sample_data/Census Data Standardization and Analysis Pipeline/census_2011.xlsx"
census = pd.read_excel(path)

# Task 1: Rename the Column names

In [6]:
#renaming_column

rename_column= {
"State name" : "State/UT",
"District name"  : "District",
"Male_Literate" : "Literate_Male",
"Female_Literate" : "Literate_Female",
"Rural_Households"  : "Households_Rural",
"Urban_Households"  : "Households_Urban",
"Age_Group_0_29" : "Young_and_Adult",
"Age_Group_30_49" : "Middle_Aged",
"Age_Group_50" : "Senior_Citizen",
"Age not stated" : "Age_Not_Stated"
}

census.rename(columns=rename_column, inplace=True)

#Printing the renamed columns

for renamed_col in census:
    print(renamed_col)

District code
State/UT
District
Population
Male
Female
Literate
Literate_Male
Literate_Female
SC
Male_SC
Female_SC
ST
Male_ST
Female_ST
Workers
Male_Workers
Female_Workers
Main_Workers
Marginal_Workers
Non_Workers
Cultivator_Workers
Agricultural_Workers
Household_Workers
Other_Workers
Hindus
Muslims
Christians
Sikhs
Buddhists
Jains
Others_Religions
Religion_Not_Stated
LPG_or_PNG_Households
Housholds_with_Electric_Lighting
Households_with_Internet
Households_with_Computer
Households_Rural
Households_Urban
Households
Below_Primary_Education
Primary_Education
Middle_Education
Secondary_Education
Higher_Education
Graduate_Education
Other_Education
Literate_Education
Illiterate_Education
Total_Education
Young_and_Adult
Middle_Aged
Senior_Citizen
Age_Not_Stated
Households_with_Bicycle
Households_with_Car_Jeep_Van
Households_with_Radio_Transistor
Households_with_Scooter_Motorcycle_Moped
Households_with_Telephone_Mobile_Phone_Landline_only
Households_with_Telephone_Mobile_Phone_Mobile_only
Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car
Households_with_Television
Households_with_Telephone_Mobile_Phone
Households_with_Telephone_Mobile_Phone_Both
Condition_of_occupied_census_houses_Dilapidated_Households
Households_with_separate_kitchen_Cooking_inside_house
Having_bathing_facility_Total_Households
Having_latrine_facility_within_the_premises_Total_Households
Ownership_Owned_Households
Ownership_Rented_Households
Type_of_bathing_facility_Enclosure_without_roof_Households
Type_of_fuel_used_for_cooking_Any_other_Households
Type_of_latrine_facility_Pit_latrine_Households
Type_of_latrine_facility_Other_latrine_Households
Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households
Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households
Not_having_bathing_facility_within_the_premises_Total_Households
Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households
Main_source_of_drinking_water_Un_covered_well_Households
Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households
Main_source_of_drinking_water_Spring_Households
Main_source_of_drinking_water_River_Canal_Households
Main_source_of_drinking_water_Other_sources_Households
Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households
Location_of_drinking_water_source_Near_the_premises_Households
Location_of_drinking_water_source_Within_the_premises_Households
Main_source_of_drinking_water_Tank_Pond_Lake_Households
Main_source_of_drinking_water_Tapwater_Households
Main_source_of_drinking_water_Tubewell_Borehole_Households
Household_size_1_person_Households
Household_size_2_persons_Households
Household_size_1_to_2_persons
Household_size_3_persons_Households
Household_size_3_to_5_persons_Households
Household_size_4_persons_Households
Household_size_5_persons_Households
Household_size_6_8_persons_Households
Household_size_9_persons_and_above_Households
Location_of_drinking_water_source_Away_Households
Married_couples_1_Households
Married_couples_2_Households
Married_couples_3_Households
Married_couples_3_or_more_Households
Married_couples_4_Households
Married_couples_5__Households
Married_couples_None_Households
Power_Parity_Less_than_Rs_45000
Power_Parity_Rs_45000_90000
Power_Parity_Rs_90000_150000
Power_Parity_Rs_45000_150000
Power_Parity_Rs_150000_240000
Power_Parity_Rs_240000_330000
Power_Parity_Rs_150000_330000
Power_Parity_Rs_330000_425000
Power_Parity_Rs_425000_545000
Power_Parity_Rs_330000_545000
Power_Parity_Above_Rs_545000
Total_Power_Parity

#Task 2: Renaming State/UT Names

In [7]:
#Function to convert the 1st letter caps then using 'and' in lower case
def uni_case(value):
    new = value.split()
    changed_val = []

    for word in new:
        if word.lower() == 'and':
            changed_val.append('and')
        else:
            changed_val.append(word.capitalize())

    return ' '.join(changed_val)

# Applying uni_case function to the 'State/UT' column in the DataFrame
census['State/UT'] = census['State/UT'].apply(uni_case)

#Printing the first 10 rows
print(census['State/UT'].head(10))

0    Jammu and Kashmir
1    Jammu and Kashmir
2    Jammu and Kashmir
3    Jammu and Kashmir
4    Jammu and Kashmir
5    Jammu and Kashmir
6    Jammu and Kashmir
7    Jammu and Kashmir
8    Jammu and Kashmir
9    Jammu and Kashmir
Name: State/UT, dtype: object

# Task 3: New State/UT formation

In [9]:
#Opening the text file that has the list of district name of Telangana state
with open(r"/content/sample_data/Census Data Standardization and Analysis Pipeline/Telangana.txt",'r') as file:
    districts_tel = file.read().splitlines()

print(districts_tel)

#State name changed to Telangana for the listed district
census.loc[census['District'].isin(districts_tel), 'State/UT'] = 'Telangana'

#Changing state name to ladakh for the district Leh and Kargil
census.loc[census['District'].isin(['Leh','Kargil']), 'State/UT'] = 'Ladakh'

#Lists after the changes made
census[census["State/UT"].isin(["Telangana","Ladakh"])]

['Adilabad', 'Nizamabad', 'Karimnagar', 'Medak', 'Hyderabad', 'Rangareddy', 'Mahbubnagar', 'Nalgonda', 'Warangal', 'Khammam']

,District code,State/UT,District,Population,Male,Female,Literate,Literate_Male,Literate_Female,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
2,3,Ladakh,Leh,133487.0,78971.0,54516.0,93770.0,62834.0,30936.0,488.0,...,46.0,122.0,15.0,22.0,NaN,20.0,NaN,NaN,17.0,242.0
3,4,Ladakh,Kargil,140802.0,NaN,63017.0,NaN,56301.0,29935.0,18.0,...,27.0,114.0,12.0,18.0,30.0,19.0,3.0,22.0,7.0,214.0
531,532,Telangana,Adilabad,2741239.0,NaN,1371642.0,1483347.0,856350.0,626997.0,488596.0,...,1266.0,2870.0,84.0,122.0,206.0,134.0,213.0,347.0,109.0,4181.0
532,533,Telangana,Nizamabad,2551335.0,1250641.0,1300694.0,1389810.0,790214.0,599596.0,371074.0,...,931.0,2399.0,61.0,60.0,121.0,71.0,105.0,176.0,100.0,NaN
533,534,Telangana,Karimnagar,3776269.0,1880800.0,1895469.0,2206829.0,1257238.0,949591.0,709757.0,...,1420.0,3583.0,128.0,99.0,227.0,119.0,173.0,292.0,186.0,5251.0
534,535,Telangana,Medak,3033288.0,1523030.0,1510258.0,1637137.0,953406.0,683731.0,537947.0,...,997.0,2656.0,84.0,59.0,143.0,71.0,102.0,173.0,116.0,3874.0
535,536,Telangana,Hyderabad,3943323.0,2018575.0,1924748.0,2892155.0,1542688.0,1349467.0,247927.0,...,3204.0,5212.0,1708.0,494.0,2202.0,NaN,860.0,1531.0,1710.0,11071.0
536,537,Telangana,Rangareddy,5296741.0,2701008.0,2595733.0,NaN,1948784.0,1589244.0,652042.0,...,2912.0,5426.0,528.0,373.0,901.0,438.0,650.0,1088.0,603.0,NaN
537,538,Telangana,Mahbubnagar,4053028.0,2050386.0,2002642.0,1940646.0,1158386.0,782260.0,708954.0,...,1137.0,3241.0,70.0,54.0,124.0,65.0,95.0,160.0,102.0,4695.0
538,539,Telangana,Nalgonda,3488809.0,1759772.0,1729037.0,2001019.0,1160757.0,840262.0,637385.0,...,1106.0,3043.0,NaN,72.0,136.0,84.0,125.0,209.0,113.0,4468.0
539,540,Telangana,Warangal,3512576.0,1759281.0,1753295.0,2065023.0,1179790.0,885233.0,616102.0,...,1203.0,3139.0,135.0,93.0,228.0,112.0,162.0,274.0,185.0,4762.0
540,541,Telangana,Khammam,2797370.0,1390988.0,1406382.0,1630234.0,901640.0,728594.0,462896.0,...,1012.0,2596.0,75.0,78.0,153.0,92.0,136.0,NaN,127.0,3836.0

# Task 4: Find and process Missing Data

In [ ]:
#Missing column in percentage
missing_data_per = census.isnull().sum()/len(census)
for column, percentage in missing_data_per.items():
    print(f'{column} : {percentage:.2%}')

#To fill missing data

#Population = Male + Female

to_fill_Population = (census['Male'].notnull() &
                      census['Population'].isnull() &
                      census['Female'].notnull())

census.loc[to_fill_Population, 'Population'] = census['Male'] + census['Female']


to_fill_Male = (census['Female'].notnull() &
                census['Population'].notnull() &
                census['Male'].isnull())

census.loc[to_fill_Male, 'Male'] = census['Population'] - census['Female']

to_fill_Female = (census['Male'].notnull() &
                  census['Population'].notnull() &
                  census['Female'].isnull())

census.loc[to_fill_Female, 'Female'] = census['Population'] - census['Male']

#Literate = Literate_Male + Literate_Female

to_fill_Literate = (census['Literate_Male'].notnull() &
                    census['Literate'].isnull() &
                    census['Literate_Female'].notnull())

census.loc[to_fill_Literate, 'Literate'] = census['Literate_Male'] + census['Literate_Female']


to_fill_Literate_Male = (census['Literate_Female'].notnull() &
                         census['Literate'].notnull() &
                         census['Literate_Male'].isnull())

census.loc[to_fill_Literate_Male, 'Literate_Male'] = census['Literate'] - census['Literate_Female']

to_fill_Literate_Female = (census['Literate_Male'].notnull() &
                           census['Literate'].notnull() &
                           census['Literate_Female'].isnull())

census.loc[to_fill_Literate_Female, 'Literate_Female'] = census['Literate'] - census['Literate_Male']

#SC = Male_SC + Female_SC

to_fill_SC = (census['Male_SC'].notnull() &
              census['SC'].isnull() &
              census['Female_SC'].notnull())

census.loc[to_fill_SC, 'SC'] = census['Male_SC'] + census['Female_SC']


to_fill_Male_SC = (census['Female_SC'].notnull() &
                   census['SC'].notnull() &
                   census['Male_SC'].isnull())

census.loc[to_fill_Male_SC, 'Male_SC'] = census['SC'] - census['Female_SC']

to_fill_Female_SC = (census['Male_SC'].notnull() &
                     census['SC'].notnull() &
                     census['Female_SC'].isnull())

census.loc[to_fill_Female_SC, 'Female_SC'] = census['SC'] - census['Male_SC']

#ST = Male_ST + Female_ST

to_fill_ST = (census['Male_ST'].notnull() &
              census['ST'].isnull() &
              census['Female_ST'].notnull())

census.loc[to_fill_ST, 'ST'] = census['Male_ST'] + census['Female_ST']

to_fill_Male_ST = (census['Female_ST'].notnull() &
                   census['ST'].notnull() &
                   census['Male_ST'].isnull())

census.loc[to_fill_Male_ST, 'Male_ST'] = census['ST'] - census['Female_ST']

to_fill_Female_ST = (census['Male_ST'].notnull() &
                     census['ST'].notnull() &
                     census['Female_ST'].isnull())

census.loc[to_fill_Female_ST, 'Female_ST'] = census['ST'] - census['Male_ST']

#Workers = Male_Workers + Female_Workers

to_fill_Workers = (census['Male_Workers'].notnull() &
                   census['Workers'].isnull() &
                   census['Female_Workers'].notnull())

census.loc[to_fill_Workers, 'Workers'] = census['Male_Workers'] + census['Female_Workers']

to_fill_Male_Workers = (census['Female_Workers'].notnull() &
                        census['Workers'].notnull() &
                        census['Male_Workers'].isnull())

census.loc[to_fill_Male_Workers, 'Male_Workers'] = census['Workers'] - census['Female_Workers']

to_fill_Female_Workers = (census['Male_Workers'].notnull() &
                          census['Workers'].notnull() &
                          census['Female_Workers'].isnull())

census.loc[to_fill_Female_Workers, 'Female_Workers'] = census['Workers'] - census['Male_Workers']

#Population = Main_Workers + Marginal_Workers + Non_Workers

to_fill_Main_Workers = (census['Population'].notnull() &
                        census['Main_Workers'].isnull() &
                        census['Marginal_Workers'].notnull() &
                        census['Non_Workers'].notnull())

census.loc[to_fill_Main_Workers, 'Main_Workers'] = census['Population'] - census['Marginal_Workers'] - census['Non_Workers']


to_fill_Marginal_Workers = (census['Population'].notnull() &
                            census['Marginal_Workers'].isnull() &
                            census['Main_Workers'].notnull() &
                            census['Non_Workers'].notnull())

census.loc[to_fill_Marginal_Workers, 'Marginal_Workers'] = census['Population'] - census['Main_Workers'] - census['Non_Workers']

to_fill_Non_Workers = (census['Population'].notnull() &
                       census['Marginal_Workers'].notnull() &
                       census['Non_Workers'].isnull() &
                       census['Main_Workers'].notnull())

census.loc[to_fill_Non_Workers, 'Non_Workers'] = census['Population'] - census['Main_Workers'] - census['Marginal_Workers']

#Workers = Cultivator_Workers + Agricultural_Workers + Household_Workers + Other_Workers

to_fill_Cultivator_Workers = (census['Cultivator_Workers'].isnull() &
                              census['Workers'].notnull() &
                              census['Agricultural_Workers'].notnull() &
                              census['Household_Workers'].notnull() &
                              census['Other_Workers'].notnull())

census.loc[to_fill_Cultivator_Workers, 'Cultivator_Workers'] = census['Workers'] - census['Agricultural_Workers'] - census['Household_Workers'] - census['Other_Workers']


to_fill_Agricultural_Workers = (census['Agricultural_Workers'].isnull() &
                                census['Workers'].notnull() &
                                census['Cultivator_Workers'].notnull() &
                                census['Household_Workers'].notnull() &
                                census['Other_Workers'].notnull())

census.loc[to_fill_Agricultural_Workers, 'Agricultural_Workers'] = census['Workers'] - census['Cultivator_Workers'] - census['Household_Workers'] - census['Other_Workers']

to_fill_Household_Workers = (census['Household_Workers'].isnull() &
                             census['Workers'].notnull() &
                             census['Agricultural_Workers'].notnull() &
                             census['Cultivator_Workers'].notnull() &
                             census['Other_Workers'].notnull())

census.loc[to_fill_Household_Workers, 'Household_Workers'] = census['Workers'] - census['Agricultural_Workers'] - census['Cultivator_Workers'] - census['Other_Workers']

to_fill_Other_Workers = (census['Other_Workers'].isnull() &
                         census['Workers'].notnull() &
                         census['Agricultural_Workers'].notnull() &
                         census['Household_Workers'].notnull() &
                         census['Cultivator_Workers'].notnull())

census.loc[to_fill_Other_Workers, 'Other_Workers'] = census['Workers'] - census['Agricultural_Workers'] - census['Household_Workers'] - census['Cultivator_Workers']

#Population = Hindus + Muslims + Christians + Sikhs + Buddhists + Jains + Others_Religions + Religion_Not_Stated


to_fill_Hindus = (census['Hindus'].isnull() &
                  census['Population'].notnull() &
                  census['Muslims'].notnull() &
                  census['Christians'].notnull() &
                  census['Sikhs'].notnull() &
                  census['Buddhists'].notnull() &
                  census['Jains'].notnull() &
                  census['Others_Religions'].notnull() &
                  census['Religion_Not_Stated'].notnull())

census.loc[to_fill_Hindus, 'Hindus'] = census['Population'] - census['Muslims'] - census['Christians'] - census['Sikhs'] - census['Buddhists'] - census['Jains'] - census['Others_Religions'] - census['Religion_Not_Stated']


to_fill_Muslims = (census['Muslims'].isnull() &
                   census['Population'].notnull() &
                   census['Hindus'].notnull() &
                   census['Christians'].notnull() &
                   census['Sikhs'].notnull() &
                   census['Buddhists'].notnull() &
                   census['Jains'].notnull() &
                   census['Others_Religions'].notnull() &
                   census['Religion_Not_Stated'].notnull())

census.loc[to_fill_Muslims, 'Muslims'] = census['Population'] - census['Hindus'] - census['Christians'] - census['Sikhs'] - census['Buddhists'] - census['Jains'] - census['Others_Religions'] - census['Religion_Not_Stated']

to_fill_Christians = (census['Christians'].isnull() &
                      census['Population'].notnull() &
                      census['Muslims'].notnull() &
                      census['Hindus'].notnull() &
                      census['Sikhs'].notnull() &
                      census['Buddhists'].notnull() &
                      census['Jains'].notnull() &
                      census['Others_Religions'].notnull() &
                      census['Religion_Not_Stated'].notnull())

census.loc[to_fill_Christians, 'Christians'] = census['Population'] - census['Muslims'] - census['Hindus'] - census['Sikhs'] - census['Buddhists'] - census['Jains'] - census['Others_Religions'] - census['Religion_Not_Stated']

to_fill_Sikhs = (census['Sikhs'].isnull() &
                 census['Population'].notnull() &
                 census['Muslims'].notnull() &
                 census['Christians'].notnull() &
                 census['Hindus'].notnull()&
                 census['Buddhists'].notnull() &
                 census['Jains'].notnull() &
                 census['Others_Religions'].notnull() &
                 census['Religion_Not_Stated'].notnull())

census.loc[to_fill_Sikhs, 'Sikhs'] = census['Population'] - census['Muslims'] - census['Christians'] - census['Hindus'] - census['Buddhists'] - census['Jains'] - census['Others_Religions'] - census['Religion_Not_Stated']

to_fill_Buddhists = (census['Buddhists'].isnull() &
                     census['Population'].notnull() &
                     census['Muslims'].notnull() &
                     census['Christians'].notnull() &
                     census['Hindus'].notnull()&
                     census['Sikhs'].notnull() &
                     census['Jains'].notnull() &
                     census['Others_Religions'].notnull() &
                     census['Religion_Not_Stated'].notnull())

census.loc[to_fill_Buddhists, 'Buddhists'] = census['Population'] - census['Muslims'] - census['Christians'] - census['Hindus'] - census['Sikhs'] - census['Jains'] - census['Others_Religions'] - census['Religion_Not_Stated']

to_fill_Jains = (census['Jains'].isnull() &
                 census['Population'].notnull() &
                 census['Muslims'].notnull() &
                 census['Christians'].notnull() &
                 census['Hindus'].notnull()&
                 census['Sikhs'].notnull() &
                 census['Buddhists'].notnull() &
                 census['Others_Religions'].notnull() &
                 census['Religion_Not_Stated'].notnull())

census.loc[to_fill_Jains, 'Jains'] = census['Population'] - census['Muslims'] - census['Christians'] - census['Hindus'] - census['Sikhs'] - census['Buddhists'] - census['Others_Religions'] - census['Religion_Not_Stated']

to_fill_Others_Religions = (census['Others_Religions'].isnull() &
                            census['Population'].notnull() &
                            census['Muslims'].notnull() &
                            census['Christians'].notnull() &
                            census['Hindus'].notnull()&
                            census['Sikhs'].notnull() &
                            census['Buddhists'].notnull() &
                            census['Jains'].notnull() &
                            census['Religion_Not_Stated'].notnull())

census.loc[to_fill_Others_Religions, 'Others_Religions'] = census['Population'] - census['Muslims'] - census['Christians'] - census['Hindus'] - census['Sikhs'] - census['Buddhists'] - census['Jains'] - census['Religion_Not_Stated']

to_fill_Religion_Not_Stated = (census['Religion_Not_Stated'].isnull() &
                               census['Population'].notnull() &
                               census['Muslims'].notnull() &
                               census['Christians'].notnull() &
                               census['Hindus'].notnull()&
                               census['Sikhs'].notnull() &
                               census['Buddhists'].notnull() &
                               census['Jains'].notnull() &
                               census['Others_Religions'].notnull())

census.loc[to_fill_Religion_Not_Stated, 'Religion_Not_Stated'] = census['Population'] - census['Muslims'] - census['Christians'] - census['Hindus'] - census['Sikhs'] - census['Buddhists'] - census['Jains'] - census['Others_Religions']

#Households = Households_Rural + Households_Urban

to_fill_Households = (census['Households_Rural'].notnull() &
                      census['Households'].isnull() &
                      census['Households_Urban'].notnull())

census.loc[to_fill_Households, 'Households'] = census['Households_Rural'] + census['Households_Urban']

to_fill_Households_Rural = (census['Households_Urban'].notnull() &
                      census['Households'].notnull() &
                      census['Households_Rural'].isnull())

census.loc[to_fill_Households_Rural, 'Households_Rural'] = census['Households'] - census['Households_Urban']

to_fill_Households_Urban = (census['Households_Rural'].notnull() &
                      census['Households'].notnull() &
                      census['Households_Urban'].isnull())

census.loc[to_fill_Households_Urban, 'Households_Urban'] = census['Households'] - census['Households_Rural']

#Literate_Education = Below_Primary_Education + Primary_Education + Middle_Education + Secondary_Education + Higher_Education + Graduate_Education + Other_Education


to_fill_Below_Primary_Education = (census['Below_Primary_Education'].isnull() &
                                   census['Literate_Education'].notnull() &
                                   census['Primary_Education'].notnull() &
                                   census['Middle_Education'].notnull() &
                                   census['Secondary_Education'].notnull() &
                                   census['Higher_Education'].notnull() &
                                   census['Graduate_Education'].notnull() &
                                   census['Other_Education'].notnull())

census.loc[to_fill_Below_Primary_Education, 'Below_Primary_Education'] = census['Literate_Education'] - census['Primary_Education'] - census['Middle_Education'] - census['Secondary_Education'] - census['Higher_Education'] - census['Graduate_Education']

to_fill_Primary_Education = (census['Primary_Education'].isnull() &
                             census['Literate_Education'].notnull() &
                             census['Below_Primary_Education'].notnull() &
                             census['Middle_Education'].notnull() &
                             census['Secondary_Education'].notnull() &
                             census['Higher_Education'].notnull() &
                             census['Graduate_Education'].notnull() &
                             census['Other_Education'].notnull())

census.loc[to_fill_Primary_Education, 'Primary_Education'] = census['Literate_Education'] - census['Below_Primary_Education'] - census['Middle_Education'] - census['Secondary_Education'] - census['Higher_Education'] - census['Graduate_Education']

to_fill_Middle_Education = (census['Middle_Education'].isnull() &
                            census['Literate_Education'].notnull() &
                            census['Primary_Education'].notnull() &
                            census['Below_Primary_Education'].notnull() &
                            census['Secondary_Education'].notnull() &
                            census['Higher_Education'].notnull() &
                            census['Graduate_Education'].notnull() &
                            census['Other_Education'].notnull())

census.loc[to_fill_Middle_Education, 'Middle_Education'] = census['Literate_Education'] - census['Primary_Education'] - census['Below_Primary_Education'] - census['Secondary_Education'] - census['Higher_Education'] - census['Graduate_Education'] - census['Other_Education']

to_fill_Secondary_Education = (census['Secondary_Education'].isnull() &
                               census['Literate_Education'].notnull() &
                               census['Primary_Education'].notnull() &
                               census['Middle_Education'].notnull() &
                               census['Below_Primary_Education'].notnull()&
                               census['Higher_Education'].notnull() &
                               census['Graduate_Education'].notnull() &
                               census['Other_Education'].notnull())

census.loc[to_fill_Secondary_Education, 'Secondary_Education'] = census['Literate_Education'] - census['Primary_Education'] - census['Middle_Education'] - census['Below_Primary_Education'] - census['Higher_Education'] - census['Graduate_Education'] - census['Other_Education']

to_fill_Higher_Education = (census['Higher_Education'].isnull() &
                            census['Literate_Education'].notnull() &
                            census['Primary_Education'].notnull() &
                            census['Middle_Education'].notnull() &
                            census['Below_Primary_Education'].notnull()&
                            census['Secondary_Education'].notnull() &
                            census['Graduate_Education'].notnull() &
                            census['Other_Education'].notnull())

census.loc[to_fill_Higher_Education, 'Higher_Education'] = census['Literate_Education'] - census['Primary_Education'] - census['Middle_Education'] - census['Below_Primary_Education'] - census['Secondary_Education'] - census['Graduate_Education'] - census['Other_Education'] - census['Religion_Not_Stated']

to_fill_Graduate_Education = (census['Graduate_Education'].isnull() &
                              census['Literate_Education'].notnull() &
                              census['Primary_Education'].notnull() &
                              census['Middle_Education'].notnull() &
                              census['Below_Primary_Education'].notnull()&
                              census['Secondary_Education'].notnull() &
                              census['Higher_Education'].notnull() &
                              census['Other_Education'].notnull())

census.loc[to_fill_Graduate_Education, 'Graduate_Education'] = census['Literate_Education'] - census['Primary_Education'] - census['Middle_Education'] - census['Below_Primary_Education'] - census['Secondary_Education'] - census['Higher_Education'] - census['Other_Education']

to_fill_Other_Education = (census['Other_Education'].isnull() &
                           census['Literate_Education'].notnull() &
                           census['Primary_Education'].notnull() &
                           census['Middle_Education'].notnull() &
                           census['Below_Primary_Education'].notnull()&
                           census['Secondary_Education'].notnull() &
                           census['Higher_Education'].notnull() &
                           census['Graduate_Education'].notnull())

census.loc[to_fill_Other_Education, 'Other_Education'] = census['Literate_Education'] - census['Primary_Education'] - census['Middle_Education'] - census['Below_Primary_Education'] - census['Secondary_Education'] - census['Higher_Education'] - census['Graduate_Education']



#Total_Education = Literate_Education + Illiterate_Education

to_fill_Total_Education = (census['Literate_Education'].notnull() &
                           census['Total_Education'].isnull() &
                           census['Illiterate_Education'].notnull())

census.loc[to_fill_Total_Education, 'Total_Education'] = census['Literate_Education'] + census['Illiterate_Education']

to_fill_Literate_Education = (census['Illiterate_Education'].notnull() &
                              census['Total_Education'].notnull() &
                              census['Literate_Education'].isnull())

census.loc[to_fill_Literate_Education, 'Literate_Education'] = census['Total_Education'] - census['Illiterate_Education']

to_fill_Illiterate_Education = (census['Literate_Education'].notnull() &
                                census['Total_Education'].notnull() &
                                census['Illiterate_Education'].isnull())

census.loc[to_fill_Illiterate_Education, 'Illiterate_Education'] = census['Total_Education'] - census['Literate_Education']


#Population  = Young_and_Adult+  Middle_Aged + Senior_Citizen + Age_Not_Stated

to_fill_Young_and_Adult = (census['Young_and_Adult'].isnull() &
                           census['Population'].notnull() &
                           census['Middle_Aged'].notnull() &
                           census['Senior_Citizen'].notnull() &
                           census['Age_Not_Stated'].notnull())

census.loc[to_fill_Young_and_Adult, 'Young_and_Adult'] = census['Population'] - census['Middle_Aged'] - census['Senior_Citizen'] - census['Age_Not_Stated']

to_fill_Middle_Aged = (census['Middle_Aged'].isnull() &
                       census['Population'].notnull() &
                       census['Young_and_Adult'].notnull() &
                       census['Senior_Citizen'].notnull() &
                       census['Age_Not_Stated'].notnull())

census.loc[to_fill_Middle_Aged, 'Middle_Aged'] = census['Population'] - census['Young_and_Adult'] - census['Senior_Citizen'] - census['Age_Not_Stated']

to_fill_Senior_Citizen = (census['Senior_Citizen'].isnull() &
                          census['Population'].notnull() &
                          census['Middle_Aged'].notnull() &
                          census['Young_and_Adult'].notnull() &
                          census['Age_Not_Stated'].notnull())

census.loc[to_fill_Senior_Citizen, 'Senior_Citizen'] = census['Population'] - census['Middle_Aged'] - census['Young_and_Adult'] - census['Age_Not_Stated']

to_fill_Age_Not_Stated = (census['Age_Not_Stated'].isnull() &
                          census['Population'].notnull() &
                          census['Middle_Aged'].notnull() &
                          census['Senior_Citizen'].notnull() &
                          census['Young_and_Adult'].notnull())

census.loc[to_fill_Age_Not_Stated, 'Age_Not_Stated'] = census['Population'] - census['Middle_Aged'] - census['Senior_Citizen'] - census['Young_and_Adult']

#Calculating the missing values after filling
missing_data_after = census.isnull().sum()/len(census)
for column, percentage in missing_data_after.items():
    print(f'{column} : {percentage:.2%}')

# Comparing the missing value

In [ ]:
for column in census.columns:
    percentage_before = missing_data_per[column] * 100
    percentage_after = missing_data_after[column] * 100
    print(f'{column}: Before {percentage_before:.2f}% ----> After {percentage_after:.2f}%')

#Saving Data to MongoDB

In [ ]:
from pymongo import MongoClient

# Connecting to MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['testdb']
collection = db['census']

# Converting DataFrame to dictionary format
data_dict = census.to_dict("records")

# Inserting data into MongoDB
collection.insert_many(data_dict)

# opening the collection
for data in collection.find():
    print(data)

# Task 6: Database connection and data upload

In [ ]:
from sqlalchemy import create_engine


mongo_data = list(collection.find())

# Remove the MongoDB ObjectId
for record in mongo_data:
    record.pop('_id', None)


# Coverting MongoDB data to dataframe
census_mtos = pd.DataFrame(mongo_data)

#Defining function to list out the lengthy column names
def print_lengthy_columns(census_mtos, max_length=30):
    lengthy_columns = [col for col in census.columns if len(col) > max_length]

    if lengthy_columns:
        for col in lengthy_columns:
            print(f"- {col}")
    else:
        print("No lengthy columns found.")

print_lengthy_columns(census_mtos)


#renaming column name for the lengthy columns

rename_lengthy_column= {
"Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households" : "Households_Night_Soil_disposed into_Open_Drain",
"Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households"  : "Households_Flush_Latrine_connect_to_Other_System",
"Not_having_bathing_facility_within_the_premises_Total_Households" : "Households_Without_Bathing_Facility",
"Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households" : "Households_Without_Latrine_facility",
"Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households"  : "Households_Handpump_Tubewell_Borewell_Water",
"Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households"  : "Households_Natural_Water_Sources",
"Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car": "Households_Comprehensive_Electronics_Vehicles"
}

census_mtos.rename(columns=rename_lengthy_column, inplace=True)

#Listing the column of the dataframe
for col in census_mtos:
    print(col)

#MySQL Database credentials
username = 'root'
password = 'Reyno#2431'
host = 'localhost'
port = 3306
database = 'test'


# Creating the engine
engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}')

#Loading data to MySQL
census_mtos.to_sql('census_mysql', con=engine, if_exists='replace', index=False)